baseurl         = "/"
theme           = "caspertwo"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 10
#SectionPagesMenu = "main"

[params]
  title       = "Field Engineer site"
  subtitle    = "raccolta di dati tecnici"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "eueung"

  logo = ""
  #orgName = "DS"
  #orgWebsite = "https://www.telematika.org"
  #orgDescription = "Here is a description placeholder for your org"

  author = "DS"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
  name = "google"
  url = "https://google.com/"
  weight = 3
  
  [[menu.icon]]
    url = "mailto:dsgardello@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dsgardello/"
    name = "github"
    weight = 2
