baseurl         = "/"
theme           = "casper3"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 10
#SectionPagesMenu = "main"

[params]
  title       = "Field Engineer site"
  subtitle    = "raccolta di dati tecnici"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
    author = "Daniele Sgardello"
    description = "raccolta di dati tecnici"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    body_classes = "georgia bg-near-white"
    show_reading_time = true    
    #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
    recent_posts_number = 2
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:dsgardello@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dsgardello/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5

 
