title = "Field Engineer site"
description = "raccolta di dati tecnici"
baseURL = "/"
languageCode = "en-us"
theme = "ananke"
DefaultContentLanguage = "en"

SectionPagesMenu = "main"
[taxonomies]
    tag = "tags"
    archive = "archives"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
home = [ "HTML", "RSS"]

[params]
    author = "Daniele Sgardello"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    body_classes = "georgia bg-near-white"
    show_reading_time = true    
    featured_image = "/images/default.jpg"
    recent_posts_number = 4
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:dsgardello@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dsgardello/"
    name = "github"
    weight = 2
